language: node_js
node_js:
  - "5"
  - "6"
  - "8"
  - "10"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  - "npm run-script travis-cover"
after_script:
  - "npm install coveralls && cat ./coverage/lcov.info | coveralls"